# Generated by Django 4.1.2 on 2023-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.PositiveIntegerField(),
        ),
    ]
