# Generated by Django 4.1.2 on 2023-04-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_breakout_category_catering_room_venue_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakout',
            options={'verbose_name_plural': '_Breakout'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '_Categories'},
        ),
        migrations.AlterModelOptions(
            name='catering',
            options={'verbose_name_plural': '_Catering'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': '_Room'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'verbose_name_plural': '_ Venues'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
