# Generated by Django 4.1.2 on 2023-04-08 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_breakout_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'verbose_name_plural': '_Venues'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile'),
            preserve_default=False,
        ),
    ]
