# Generated by Django 4.1.2 on 2023-04-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_venue_options_remove_reservation_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirmation',
            field=models.CharField(max_length=10),
        ),
    ]
