# Generated by Django 4.1.2 on 2023-04-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_reservation_client_reservation_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.IntegerField(),
        ),
    ]
