# Generated by Django 4.1.2 on 2023-04-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_reservation_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='profile',
            new_name='client',
        ),
    ]
