# Generated by Django 4.1.2 on 2023-04-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_reservation_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='profile',
        ),
    ]
