# Generated by Django 4.1.2 on 2022-11-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.CharField(default=300, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='event_title',
            field=models.CharField(default=300, max_length=300),
            preserve_default=False,
        ),
    ]
