# Generated by Django 4.1.2 on 2022-11-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_breakout_catering_room_venue_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(),
        ),
    ]
