# Generated by Django 4.1.2 on 2022-11-23 21:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0008_alter_booking_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Customer',
        ),
    ]
