# Generated by Django 4.1.2 on 2022-11-23 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_rename_booking_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='owner',
        ),
    ]
