# Generated by Django 4.1.2 on 2022-11-26 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_user_customer'),
        ('booking', '0010_remove_customer_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(default=10000, on_delete=django.db.models.deletion.CASCADE, to='authentication.customer'),
            preserve_default=False,
        ),
    ]
