# Generated by Django 4.1.2 on 2022-11-27 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_user_customer'),
        ('booking', '0011_remove_customer_contact_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Booking',
        ),
    ]
