# Generated by Django 4.1.2 on 2022-11-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_booking_owner_alter_user_is_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='owner',
            new_name='user',
        ),
    ]
