# Generated by Django 4.1.2 on 2022-11-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_rename_owner_booking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
