# Generated by Django 4.1.3 on 2022-12-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_remove_booking_user_booking_contact_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='pay',
            field=models.CharField(default=300, max_length=300),
            preserve_default=False,
        ),
    ]
