# Generated by Django 4.1.3 on 2022-12-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_payment_booking_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pay',
        ),
    ]
