# Generated by Django 4.1.3 on 2022-12-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_remove_booking_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pay',
            field=models.CharField(default=300, max_length=300),
            preserve_default=False,
        ),
    ]
