# Generated by Django 4.1.3 on 2022-12-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_booking_pay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pay',
        ),
    ]
