# Generated by Django 4.1.2 on 2022-11-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_fullname_customer_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
