# Generated by Django 4.1.2 on 2022-11-27 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_user_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.customer')),
                ('is_customer', models.BooleanField(default=True)),
                ('is_owner', models.BooleanField(default=True)),
            ],
            bases=('authentication.customer',),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.user')),
            ],
        ),
    ]
