# Generated by Django 4.1.2 on 2022-11-29 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_remove_booking_user_booking_contact_address_and_more'),
        ('authentication', '0006_user_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='customer_ptr',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
